version: '3.9'

services:
  app:
    build:
      context: .
    ports:
      - 9000:8000
    volumes:
        - ./app:/app
        - ./static:/static
    environment:
      - DEBUG=1
    command: python manage.py runserver 0.0.0.0:8000
